### ISSUE TITLE
Possible bug in `noiseSeed`?

### ISSUE THREAD

**Issue by parazyd** [symbolicsoft/kyber-k2so#5] opened 2023-12-06 11:04 UTC
Hey. I'm noticing some behaviour that might not be intended, or at least it is undocumented.

In the code at: https://github.com/symbolicsoft/kyber-k2so/blob/master/indcpa.go#L165

```
publicSeed, noiseSeed := buf[:paramsSymBytes], buf[paramsSymBytes:]
a, err := indcpaGenMatrix(publicSeed, false, paramsK)
```

After running `indcpaGenMatrix`, `noiseSeed` changes its first two bytes.
Is this the intended behaviour?

I replicate this deterministically by disabling any random sampling in the code.

**Comment by parazyd** [comment] 2023-12-06 11:06
Here's a quick patch that can let you see what is happening: 

```
diff --git a/indcpa.go b/indcpa.go
index 497a0e1..ee86fff 100644
--- a/indcpa.go
+++ b/indcpa.go
@@ -5,6 +5,7 @@ package kyberk2so
 
 import (
 	"crypto/rand"
+	"fmt"
 
 	"golang.org/x/crypto/sha3"
 )
@@ -163,7 +164,11 @@ func indcpaKeypair(paramsK int) ([]byte, []byte, error) {
 	buf = buf[:0]
 	buf = h.Sum(buf)
 	publicSeed, noiseSeed := buf[:paramsSymBytes], buf[paramsSymBytes:]
+	fmt.Println("publicSeed before =", publicSeed)
+	fmt.Println("noiseSeed before =", noiseSeed)
 	a, err := indcpaGenMatrix(publicSeed, false, paramsK)
+	fmt.Println("publicSeed after =", publicSeed)
+	fmt.Println("noiseSeed after =", noiseSeed)
 	if err != nil {
 		return []byte{}, []byte{}, err
 	}
```

**Comment by parazyd** [comment] 2023-12-12 08:11
@nadimkobeissi

**Comment by nadimkobeissi** [comment] 2023-12-12 20:18
Thank you very much for this excellent and valuable catch. I don't know if there's any security impact, but this seems like it should be fixed either way to adhere to the spec as much as possible.

The problem is clearly caused by incorrect buffer referencing, and your PR fixes it.

I will issue an update.

Thanks again. Great work.

**Comment by nadimkobeissi** [comment] 2023-12-12 20:23
https://github.com/symbolicsoft/kyber-k2so/releases/tag/v0.2.1

**Closed by nadimkobeissi** 2023-12-12 20:23 UTC

**Comment by parazyd** [comment] 2023-12-18 14:50
@nadimkobeissi You have reintroduced this issue in fe8543e1445563c38e03073a02efc9f109519a88

**Comment by nadimkobeissi** [comment] 2023-12-19 11:20
@parazyd Nothing to worry about, I am aware. I am working on a cleaner fix which will be pushed before the next release.
